export type AtlasDataset = {
  id:string; name:string; category:string; mission:string; instrument:string; organization:string;
  source_url:string; citation:string; version:string; product_id:string;
  period:Record<string,string|number|null>; coverage:{south:number;north:number;west:number;east:number}|null;
  pixels_per_degree:number|null; spacing_m_at_equator:number|null; unit:string; crs:string;
  longitude_convention:string; frame_note:string; data_type:string; cache:string|null;
  acquisition_status:string; numerical_queries:boolean; overlay_available:boolean; download_bytes:number;adapter:string;
  limitations:string[];
};
export type AtlasQuantity = {value:number|null;unit:string;status:string;source_id:string;version:string;
  spacing_north_m:number;spacing_east_m:number;support_north_m:number;support_east_m:number;method:string;quantity_kind:string};
export type AtlasPoint = {latitude_deg:number;longitude_deg:number;longitude_defined:boolean;pixel_center:number[];
  sample_row:number;sample_column:number;dataset_id:string;elevation:AtlasQuantity;slope:AtlasQuantity;
  reference_radius_m:number;frame_note:string;terrain_source:string;geology:GeologyQuantity|null};
export type GeologyCategory={id:number;code:string;color:string;name:string;description:string;interpretation:string;description_source_code:string;source_note:string|null};
export type GeologyQuantity={status:string;category:GeologyCategory|null;source_id:string;version:string;pixel_center:number[];frame_note:string;method:string;map_scale:number;pixels_per_degree:number};
export type AtlasView = {dataset:string;layer:string;opacity:number;compare:boolean;reveal:number};
export type AtlasLayer = {id:string;dataset_id:string;name:string;unit:string;minimum:number|null;maximum:number|null;colors:string[];categories?:GeologyCategory[];source_id:string;version:string;angular_spacing_deg:number;max_level:number;url_template:string};
export type AtlasSector={id:string;name:string;face:string;level:number;x:number;y:number;center:{longitude_deg:number;latitude_deg:number};boundary:{longitude_deg:number;latitude_deg:number}[]};
export type AreaSummary={minimum:number|null;maximum:number|null;mean:number|null;unit:string;valid_cells:number;valid_area_km2:number};
export type AreaReport={dataset_id:string;source_id:string;version:string;selected_cells:number;selected_area_km2:number;elevation:AreaSummary;slope:AreaSummary;
  area:{kind:string;latitude_deg?:number;longitude_deg?:number;radius_km?:number;south?:number;north?:number;west?:number;east?:number};
  terrain_relief_m:number|null;
  slope_distribution:{minimum_deg:number;maximum_deg:number;area_km2:number;fraction_of_valid_slope_area:number|null}[];weighting_method:string;warnings:string[];
  frame_note:string;resolution:{pixels_per_degree:number;north_south_spacing_m:number;slope_support_pixels:number}};
export type ProfileReport={dataset_id:string;source_id:string;version:string;distance_km:number;sample_spacing_km:number;
  samples:{distance_km:number;longitude_deg:number;latitude_deg:number;elevation_m:number|null;status:string}[];method:string;warnings:string[]};
export type AtlasAnalysisState={radius:string;kind:'circle'|'box';bounds:{south:string;north:string;west:string;east:string};endpoint:{latitude:string;longitude:string};report:AreaReport|null;profile:ProfileReport|null};
export type DiscoveryProvider={id:string;dataset_id:string;name:string;collection_id:string;source_url:string;note:string};
export type DiscoverySnapshot={collection_id:string;source_url:string;fetched_at:string;metadata_sha256:string;total_products:number;limit:number;note:string;
  products:{identifier:string;title:string;product_class:string;label_url:string|null;version:string|null;period:{start:string|null;stop:string|null};
    indexed_coverage:{south:string|number|null;north:string|number|null;west:string|number|null;east:string|number|null;note:string};
    files:{url:string;bytes:number|null;md5:string|null;media_type:string|null}[]}[]};
