import type {GlobeLocation} from './globe';
import type {AtlasDataset,AtlasQuantity} from './atlas';
export type SettlementSettings={radius:string;neighborhood:string;slope:string;dataset:string};
export type ScoreBand='strong'|'promising'|'mixed'|'constrained';
export type ScoreComponent={criterion:'low_slope_terrain'|'solar_visibility';label:string;weight:number;value:number|null;evaluated:boolean;contribution:number;basis:string};
export type Candidate=GlobeLocation&{id:string;radius_km:number;dataset_id:string;source_id:string;version:string;spacing_m:number;
  valid_terrain_fraction:number;low_slope_fraction:number;low_slope_area_km2:number;mean_slope_deg:number;
  solar_visibility:number|null;solar_valid_fraction:number;temperature_at_center:AtlasQuantity|null;
  evidence_group:string;tradeoff_front:number;reasons:string[];unknowns:string[];
  screening_score:number;score_band:ScoreBand;data_completeness:number;score_components:ScoreComponent[];rank_in_group:number};
export type SuitabilityReport={model_version:string;score_method:string;request:{area:GlobeLocation&{radius_km:number};max_slope_deg:number};
  candidates:Candidate[];evaluated_centers:number;supported_candidates:number;search_spacing_km:number;
  assumptions:string[];warnings:string[];sources:AtlasDataset[]};
export type NeighborhoodCell={center:[number,number];polygon:[number,number][];elevation_m:number|null;slope_deg:number|null;
  low_slope:boolean|null;solar_visibility:number|null;area_km2:number};
export type NeighborhoodReport={dataset_id:string;source_id:string;version:string;spacing_m:number;radius_km:number;max_slope_deg:number;
  center:[number,number];cells:NeighborhoodCell[];valid_terrain_fraction:number;low_slope_fraction:number|null;
  solar_visibility:number|null;solar_valid_fraction:number;method:string};
