import {chooseOverlay} from './workspace';
import {test,expect} from '@playwright/test';
import {openDestinations} from './workspace';

test('basic Moon controls disclose advanced tools and preserve best native point measurements',async({page,request})=>{
  await page.goto('/');await expect(page.getByTestId('globe-status')).toContainText('terrain ready');
  const primary=page.getByRole('navigation',{name:'Primary navigation'});
  await expect(primary.getByRole('button')).toHaveText(['Explore','Analyze','Build','Simulate']);
  const tools=page.getByRole('navigation',{name:'Global view tools'});
  await expect(tools.getByRole('button')).toHaveCount(2);
  await expect(page.getByText('Go to coordinates',{exact:true})).toHaveCount(0);
  await expect(page.getByRole('region',{name:'System activity'})).toHaveCount(0);
  await page.screenshot({path:'../artifacts/simple-moon-final.png'});
  await tools.getByRole('button',{name:'Advanced',exact:true}).click();
  await page.getByText('Go to coordinates',{exact:true}).click();
  await page.getByLabel('Globe latitude (°)',{exact:true}).fill('-89.67');
  await page.getByLabel('Globe longitude (° E)',{exact:true}).fill('129.78');
  await page.getByRole('button',{name:'Fly to coordinates',exact:true}).click();
  const native=await(await request.get('/api/sites/inspect?latitude=-89.67&longitude=129.78')).json();
  await expect(page.getByTestId('global-elevation')).toHaveText(`${native.elevation.value.toLocaleString('en-US')} m`);
  await page.getByRole('button',{name:'View scientific overlays',exact:true}).click();
  await expect(page.getByTestId('atlas-elevation')).toHaveText(`${native.elevation.value.toLocaleString('en-US')} m`);
  await expect(page.getByRole('complementary',{name:'Lunar atlas'})).toContainText('240 m native spacing');
  await chooseOverlay(page,'illumination');
  await expect(page.getByTestId('atlas-overlay-status')).toContainText('Scientific overlay ready');
  await expect(page.getByRole('button',{name:'Find settlement sites',exact:true})).toBeEnabled();
  await page.screenshot({path:'../artifacts/simple-overlay-final.png'});
  await page.getByRole('button',{name:'Close atlas',exact:true}).click();
  await openDestinations(page);await page.getByRole('button',{name:/^Lunar north pole/}).click();
  await page.getByRole('button',{name:'Overlays',exact:true}).click();
  await chooseOverlay(page,'slope');
  await expect(page.getByTestId('atlas-overlay-status')).toContainText('Scientific overlay ready');
  const resources=JSON.parse((await page.getByTestId('moon-canvas').getAttribute('data-overlay-resources'))!);
  expect(resources.retained_tiles).toBeLessThanOrEqual(32);
  await page.screenshot({path:'../artifacts/simple-north-pole-final.png'});
});
